service: klick-serverless

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  stackname: ${self:service}-${self:custom.stage}
  tablePrefix: '${self:custom.stackname}-*'
  scriptHooks:
    after:deploy:deploy:
      - ./scripts/deploy_static_files.sh ${self:custom.stackname}

provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10
  environment:
    USER_TABLE: {Ref: UsersTBL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - "Fn::Join":
            - ""
            -
              - "arn:aws:dynamodb:"
              - {Ref: "AWS::Region"}
              - ":"
              - {Ref: "AWS::AccountId"}
              - ":table/"
              - ${self:custom.tablePrefix}
        - "Fn::Join":
            - ""
            -
              - "arn:aws:dynamodb:"
              - {Ref: "AWS::Region"}
              - ":"
              - {Ref: "AWS::AccountId"}
              - ":table/"
              - ${self:custom.tablePrefix}
              - '/index/*'

functions:
  form:
    handler: functions/formHandler/handler.formHandler
    events:
      - http:
          path: form
          method: post
          cors: true

resources:
  Resources:
    UsersTBL: ${file(resources/database/user-tbl.yml)}
    WebsiteBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
  Outputs:
    WebSiteUrl:
      Value: {"Fn::GetAtt": [WebsiteBucket, WebsiteURL]}
    WebSiteBucket:
      Value: {Ref: WebsiteBucket}

plugins:
  - serverless-scriptable-plugin